replicaCount: 1
namespace: soumen
image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  name: nginx-service
  type: ClusterIP
  port: 80
  targetPort: 9000
env:
  name: prod
